name: auto-rmskin-package

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: windows-latest
    outputs:
      target: ${{ steps.create_rmskin.outputs.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create rmskin
        shell: powershell
        id: create_rmskin
        run: |
          Write-Output "Compressing archive: *"
          $target = "${{ github.event.repository.name }}.zip"
          Compress-Archive -Path ./* -DestinationPath $target
          Write-Output "Archive: $target"

          Write-Output "Writing footer..."
          $size = [long](Get-Item $target).length
          $size_bytes = [System.BitConverter]::GetBytes($size)
          Add-Content -Path $target -Value $size_bytes -Encoding Byte

          $flags = [byte]0
          Add-Content -Path $target -Value $flags -Encoding Byte

          $rmskin = [string]"RMSKIN`0"
          Add-Content -Path $target -Value $rmskin -NoNewLine -Encoding ASCII

          Write-Output "Changing .zip to .rmskin"
          Rename-Item -Path $target -NewName ([io.path]::ChangeExtension($target, '.rmskin'))
          $target = $target.Replace(".zip", ".rmskin")
          Write-Output "File to upload: $target"

          echo "::set-output name=target::$target"
      - name: Upload rmskin file
        uses: actions/upload-artifact@v2
        with:
          name: clockan
          path: ${{ steps.create_rmskin.outputs.target }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $(date '+%m-%d-%s')
          release_name: Release $(date '+%m-%d-%s')
          draft: false
          prerelease: false
      - name: Upload rmskin file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: $target
          asset_name: $(date '+%m-%d-%s').rmskin
          asset_content_type: application/x-rmskin