name: auto-rmskin-package

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: windows-latest
    outputs:
      target: ${{ steps.create_rmskin.outputs.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create rmskin
        shell: powershell
        id: create_rmskin
        run: |
          Write-Output "Compressing archive: *"
          $target = "${{ github.event.repository.name }}.zip"
          Compress-Archive -Path ./* -DestinationPath $target
          Write-Output "Archive: $target"
          Write-Output "Writing footer..."
          $size = [long](Get-Item $target).length
          $size_bytes = [System.BitConverter]::GetBytes($size)
          Add-Content -Path $target -Value $size_bytes -Encoding Byte
          $flags = [byte]0
          Add-Content -Path $target -Value $flags -Encoding Byte
          $rmskin = [string]"RMSKIN`0"
          Add-Content -Path $target -Value $rmskin -NoNewLine -Encoding ASCII
          Write-Output "Changing .zip to .rmskin"
          Rename-Item -Path $target -NewName ([io.path]::ChangeExtension($target, '.rmskin'))
          $target = $target.Replace(".zip", ".rmskin")
          Write-Output "File to upload: $target"
          echo "::set-output name=target::$target"
      - name: Upload rmskin file
        uses: actions/upload-artifact@v2
        with:
          name: clockan
          path: ${{ steps.create_rmskin.outputs.target }}
      # - name: Echo artifact download link
      #   run: echo "The artifact download link is: https://github.com/${{ github.repository }}/actions/artifacts/download/clockan/${{ steps.upload-rmskin-file.outputs.artifact_url }}"
      - name: Create a new GitHub Discussion
        id: create-discussion
        uses: abirismyname/create-discussion@v1.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
        with:
          title: Artifact $(date +%m-%d)-$(date +%s)
          body: |
            Artifact Link: $(date +%m-%d)-$(date +%s). Link = https://github.com/${{ github.repository }}/actions/artifacts/download/clockan/${{ steps.upload-rmskin-file.outputs.artifact_url }}
          repository-id: ${{ secrets.REPO_ID }}
          category-id: ${{ secrets.CAT_ID }}  
      - name: Print discussion url and id
        run: |
          echo discussion-id: ${{steps.create-discussion.outputs.discussion-id}} 
          echo discussion-url: ${{steps.create-discussion.outputs.discussion-url}}             