name: auto-rmskin-package

on:
  release:
    types: [created]

jobs:
  package:
    runs-on: windows-latest
    outputs:
      target: ${{ steps.create_rmskin.outputs.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Create rmskin
        shell: powershell
        id: create_rmskin
        run: |
          Write-Output "Compressing archive: *"
          $target = "${{ github.event.repository.name }}.zip"
          Compress-Archive -Path ./* -DestinationPath $target
          Write-Output "Archive: $target"

          Write-Output "Writing footer..."
          $size = [long](Get-Item $target).length
          $size_bytes = [System.BitConverter]::GetBytes($size)
          Add-Content -Path $target -Value $size_bytes -Encoding Byte

          $flags = [byte]0
          Add-Content -Path $target -Value $flags -Encoding Byte

          $rmskin = [string]"RMSKIN`0"
          Add-Content -Path $target -Value $rmskin -NoNewLine -Encoding ASCII

          Write-Output "Changing .zip to .rmskin"
          Rename-Item -Path $target -NewName ([io.path]::ChangeExtension($target, '.rmskin'))
          $target = $target.Replace(".zip", ".rmskin")
          Write-Output "File to upload: $target"

          echo "::set-output name=target::$target"
      - name: Upload rmskin file
        uses: actions/upload-artifact@v2
        with:
          name: clockan
          path: ${{ steps.create_rmskin.outputs.target }}
          artifact_name: clockan-${{ github.event.release.tag_name }}.rmskin
          target_path: ${{ github.event.release.tag_name }}